; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
board_build.mcu = ra4m1
board_build.f_cpu = 48000000L

; Libraries
lib_deps =
    256dpi/MQTT                                     ; lightweight MQTT client
    arduino-libraries/Arduino_Modulino@^0.7.0       ; modulino interactions

; Compiler flags
build_flags =
    -DARDUINO_UNOWIFIR4
    -mfpu=fpv4-sp-d16                               ; enable fpu+dsp
    -mfloat-abi=hard
    -mcpu=cortex-m4
    -O2
